In [2]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

base_url = 'https://www.flipkart.com/search?q=Iphone&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off'
HEADERS = {
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/117.0.0.0 Safari/537.36 Avast/117.0.0.0',
    'Accept-Language': 'en-US, en;q=0.5'
}

num_pages = 21

Titles = []
Prices = []
Rating = []
No_of_given_ratings = []
Display = []
Processor = []
Storage = []
Camera = []
for page in range(1, num_pages + 1):
    url = base_url + "&page=" + str(page)
    response = requests.get(url, headers=HEADERS)
    soup = BeautifulSoup(response.content, 'html.parser')

    links = soup.find_all('a', class_='_1fQZEK')
    link_list = []

    for link in links:
        link_list.append(link.get('href'))

    for link in link_list:
        response2 = requests.get('https://www.flipkart.com' + link, headers=HEADERS)
        soup2 = BeautifulSoup(response2.content, 'html.parser')

        title = soup2.find('span', class_='B_NuCI').get_text()
        storage = soup2.find('li', class_='_21Ahn-').get_text()
        rating = soup2.find('div', class_='_3LWZlK').get_text()
        no_of_ratings = soup2.find('span', class_='_2_R_DZ').get_text()
        price = soup2.find('div', class_='_30jeq3').get_text()
        specs = soup2.find_all('li', class_='_21Ahn-')
        if specs:
            storage = specs[0].get_text()
            display = specs[1].get_text() if len(specs) > 1 else ''
            camera = specs[2].get_text() if len(specs) > 2 else ''
            processor = specs[3].get_text() if len(specs) > 3 else ''

        Titles.append(title)
        Prices.append(price)
        Rating.append(rating)
        No_of_given_ratings.append(no_of_ratings)
        Storage.append(storage)
        Display.append(display)
        Camera.append(camera)
        Processor.append(processor)
data = {
    'Name': Titles,
    'Storage': Storage,
    'Display': Display,
    'Camera': Camera,
    'Processor': Processor,
    'Rating': Rating,
    'No. of Ratings': No_of_given_ratings,
    'Price': Prices
}
df = pd.DataFrame(data)
df

,Name,Storage,Display,Camera,Processor,Rating,No. of Ratings,Price
0,"APPLE iPhone 14 (Blue, 128 GB)",128 GB ROM,15.49 cm (6.1 inch) Super Retina XDR Display,12MP + 12MP | 12MP Front Camera,"A15 Bionic Chip, 6 Core Processor Processor",4.7,"1,49,154 Ratings & 5,243 Reviews","₹61,999"
1,"APPLE iPhone 14 (Starlight, 128 GB)",128 GB ROM,15.49 cm (6.1 inch) Super Retina XDR Display,12MP + 12MP | 12MP Front Camera,"A15 Bionic Chip, 6 Core Processor Processor",4.7,"1,49,154 Ratings & 5,243 Reviews","₹61,999"
2,"APPLE iPhone 14 (Midnight, 128 GB)",128 GB ROM,15.49 cm (6.1 inch) Super Retina XDR Display,12MP + 12MP | 12MP Front Camera,"A15 Bionic Chip, 6 Core Processor Processor",4.7,"1,49,154 Ratings & 5,243 Reviews","₹61,999"
3,"APPLE iPhone 14 Plus (Blue, 128 GB)",128 GB ROM,17.02 cm (6.7 inch) Super Retina XDR Display,12MP + 12MP | 12MP Front Camera,"A15 Bionic Chip, 6 Core Processor Processor",4.6,"32,985 Ratings & 1,845 Reviews","₹71,999"
4,"APPLE iPhone 14 Plus (Starlight, 128 GB)",128 GB ROM,17.02 cm (6.7 inch) Super Retina XDR Display,12MP + 12MP | 12MP Front Camera,"A15 Bionic Chip, 6 Core Processor Processor",4.6,"32,985 Ratings & 1,845 Reviews","₹71,999"
...,...,...,...,...,...,...,...,...
485,"APPLE iPhone 5C (White, 16 GB)",16 GB ROM,10.16 cm (4 inch) Retina Display,8MP Rear Camera | 1.2MP Front Camera,A6 Chip Processor,3.9,"1,327 Ratings & 265 Reviews","₹41,900"
486,"APPLE iPhone X (Silver, 64 GB)",64 GB ROM,14.73 cm (5.8 inch) Super Retina HD Display,12MP + 12MP | 7MP Front Camera,"A11 Bionic Chip with 64-bit Architecture, Neur...",4.6,"10,964 Ratings & 863 Reviews","₹91,900"
487,"APPLE iPhone 5C (Yellow, 8 GB)",8 GB ROM,10.16 cm (4 inch) Retina Display,8MP Rear Camera | 1.2MP Front Camera,A6 Chip Processor,3.9,"1,327 Ratings & 265 Reviews","₹37,500"
488,"APPLE iPhone X (Silver, 256 GB)",256 GB ROM,14.73 cm (5.8 inch) Super Retina HD Display,12MP + 12MP | 7MP Front Camera,"A11 Bionic Chip with 64-bit Architecture, Neur...",4.6,"10,964 Ratings & 863 Reviews","₹1,06,900"
489,"APPLE iPhone X (Space Gray, 256 GB)",256 GB ROM,14.73 cm (5.8 inch) Super Retina HD Display,12MP + 12MP | 7MP Front Camera,"A11 Bionic Chip with 64-bit Architecture, Neur...",4.6,"10,964 Ratings & 863 Reviews","₹1,06,900"

In [ ]:
df['Price'] = df['Price'].str.replace('₹','').str.replace(',','').astype(int)
df['No. of Ratings'] = df['No. of Ratings'].str.replace(r'\s[\d,]+ Reviews', '', regex=True)
df['No. of Ratings'] = df['No. of Ratings'].str.replace(',','')
df['No. of Ratings'] = df['No. of Ratings'].str.replace('Ratings','')
df['No. of Ratings'] = df['No. of Ratings'].str.replace('&','')

In [19]:
import re
df['No. of Ratings'] = df['No. of Ratings'].str.replace(r'[^\d,]', '', regex=True)
df['No. of Ratings'] = df['No. of Ratings'].str.replace(',', '', regex=True)
df['No. of Ratings'] = df['No. of Ratings'].astype(int)
df

,Name,Storage,Display,Camera,Processor,Rating,No. of Ratings,Price
0,"APPLE iPhone 14 (Blue, 128 GB)",128 GB ROM,15.49 cm (6.1 inch) Super Retina XDR Display,12MP + 12MP | 12MP Front Camera,"A15 Bionic Chip, 6 Core Processor Processor",4.7,149154,61999
1,"APPLE iPhone 14 (Starlight, 128 GB)",128 GB ROM,15.49 cm (6.1 inch) Super Retina XDR Display,12MP + 12MP | 12MP Front Camera,"A15 Bionic Chip, 6 Core Processor Processor",4.7,149154,61999
2,"APPLE iPhone 14 (Midnight, 128 GB)",128 GB ROM,15.49 cm (6.1 inch) Super Retina XDR Display,12MP + 12MP | 12MP Front Camera,"A15 Bionic Chip, 6 Core Processor Processor",4.7,149154,61999
3,"APPLE iPhone 14 Plus (Blue, 128 GB)",128 GB ROM,17.02 cm (6.7 inch) Super Retina XDR Display,12MP + 12MP | 12MP Front Camera,"A15 Bionic Chip, 6 Core Processor Processor",4.6,32985,71999
4,"APPLE iPhone 14 Plus (Starlight, 128 GB)",128 GB ROM,17.02 cm (6.7 inch) Super Retina XDR Display,12MP + 12MP | 12MP Front Camera,"A15 Bionic Chip, 6 Core Processor Processor",4.6,32985,71999
...,...,...,...,...,...,...,...,...
485,"APPLE iPhone 5C (White, 16 GB)",16 GB ROM,10.16 cm (4 inch) Retina Display,8MP Rear Camera | 1.2MP Front Camera,A6 Chip Processor,3.9,1327,41900
486,"APPLE iPhone X (Silver, 64 GB)",64 GB ROM,14.73 cm (5.8 inch) Super Retina HD Display,12MP + 12MP | 7MP Front Camera,"A11 Bionic Chip with 64-bit Architecture, Neur...",4.6,10964,91900
487,"APPLE iPhone 5C (Yellow, 8 GB)",8 GB ROM,10.16 cm (4 inch) Retina Display,8MP Rear Camera | 1.2MP Front Camera,A6 Chip Processor,3.9,1327,37500
488,"APPLE iPhone X (Silver, 256 GB)",256 GB ROM,14.73 cm (5.8 inch) Super Retina HD Display,12MP + 12MP | 7MP Front Camera,"A11 Bionic Chip with 64-bit Architecture, Neur...",4.6,10964,106900
489,"APPLE iPhone X (Space Gray, 256 GB)",256 GB ROM,14.73 cm (5.8 inch) Super Retina HD Display,12MP + 12MP | 7MP Front Camera,"A11 Bionic Chip with 64-bit Architecture, Neur...",4.6,10964,106900

In [20]:
df.to_csv('Flipkart_IphoneData.csv', index=False)