In [37]:
import pandas as pd

df = pd.read_csv('ffwdData.csv')
df

,Name,Descp1,Descp2,FoundedIn,FoundersName,FoundersLinkedIn,URL,Program Area,Location of Impact,Headquarters Location,Product platforms,Budget
0,1947 Partition Archive,Documenting the people’s history of India’s 19...,The 1947 Partition Archive began with the need...,2011 by,Guneeta Singh Bhalla,https://www.linkedin.com/in/guneeta,http://www.1947PartitionArchive.org,"Education, Arts & Culture, Human Rights",Global,"Berkeley, California, United States","Web, Hardware","$0 to $500,000"
1,A Way Home Washington,We believe that we can prevent and end youth h...,A Way Home Washington provides statewide suppo...,2019 by,"Sonya Campion, Tricia Raikes",https://campionadvocacyfund.org/people/sonya-...,https://awayhomewa.org/,"Human Rights, Public Service & Civic Engagement",United States,"Seattle, Washington, United States",Web,"$1,000,000 +"
2,AccesSOS,To make it possible for people with limited En...,AccesSOS was started because the founder’s Dea...,2019 by,"Gabriella M. Wong, Sarah M. Peterson","https://www.linkedin.com/in/gabriella-m/, htt...",https://accessos.io,"Health & Healthcare, Public Service & Civic En...",United States,"San Francisco, California, United States",Mobile Apps,"$0 to $500,000"
3,AbleThrive,AbleThrive makes it easier for families to fin...,"When a family faces a disability, they are oft...",2014 by,Brittany Déjean,https://sg.linkedin.com/in/brittanym,http://www.ablethrive.com,"Health & Healthcare, Public Service & Civic En...",Global,"Downingtown, Pennsylvania, United States",Web,"$0 to $500,000"
4,Acquaint,"Crowdsourcing a peaceful, more inclusive world...","Acquaint is a rewarding, inclusive, and access...",2021 by,"Katherine Mahon, Alex Szebenyi",https://www.linkedin.com/in/katherine-mahon1/...,https://www.acquaint.org?tsrc=nl1_ffwd1,"Public Service & Civic Engagement, Arts & Cult...",Global,"Bellevue, Washington, United States",Web,"$0 to $500,000"
...,...,...,...,...,...,...,...,...,...,...,...,...
716,Zariya,Zariya’s on a mission to ensure that every wom...,Zariya is an organization that addresses the p...,2015 by,"Sahar Khan, Arzav Jain, Abraham Vargheese, Jap...","https://www.linkedin.com/in/khansahar, https:...",http://www.zariyaindia.org,"Human Rights, Poverty Alleviation & Economic D...",India,"Stanford, California, United States","Web, Mobile Apps","$0 to $500,000"
717,ZAKKI (Integrity Syariah),Empowering the marginalized economic community...,"ZAKKI, is a non profit entity that focuses on ...",2018 by,Arifah Suparni,https://www.linkedin.com/in/arifah/,https://www.zakki.org,"Poverty Alleviation & Economic Development, Pu...",Indonesia,"Semarang, Indonesia","Web, Mobile Apps","$0 to $500,000"
718,YWCA Golden Gate Silicon Valley,YWCA Silicon Valley is dedicated to eliminatin...,In addition to our work in disrupting the cycl...,2017 by,"Co-founders are: Janice Zdankus, Lesley Slaton...",https://www.linkedin.com/in/janice-zdankus-a4...,https://ywca-sv.org/curated-pathways-to-innova...,"Education, Poverty Alleviation & Economic Deve...",United States,"San Jose, California, United States",Mobile Apps,"$500,000 to $1,000,000"
719,YTH,Youth + Tech + Health is the partner of choice...,Youth + Technology + Health. YTH is committed ...,2001 by,Deb Levine,https://www.linkedin.com/in/deblevine,http://yth.org,"Public Service & Civic Engagement, Health & He...","Global, Africa, Latin America, United States","Oakland , California, United States","Web, Mobile Apps, SMS","$1,000,000 +"
720,Zooniverse,The Zooniverse is a collection of web-based Ci...,The Zooniverse is the largest online platform ...,2008 by,Chris Lintott,https://www.linkedin.com/in/chris-lintott-621...,https://www.zooniverse.org/,Environment,Global,"Chicago , Illinois, United States","Web, Mobile Apps","$500,000 to $1,000,000"

In [40]:
founders_split = df['FoundersLinkedIn'].str.split(', ', expand=True)

# Renaming the new columns
founders_split.columns = [f'Founder{i+1}LinkedIn' for i in range(founders_split.shape[1])]

# Concatenating the new columns to the original DataFrame
df = pd.concat([df, founders_split], axis=1)

# Dropping the original FoundersName column
df = df.drop(['FoundersLinkedIn'], axis=1)
df

,Name,Descp1,Descp2,FoundedIn,URL,Program Area,Location of Impact,Headquarters Location,Product platforms,Budget,...,Founder11,Founder12,Founder1LinkedIn,Founder2LinkedIn,Founder3LinkedIn,Founder4LinkedIn,Founder5LinkedIn,Founder6LinkedIn,Founder7LinkedIn,Founder8LinkedIn
0,1947 Partition Archive,Documenting the people’s history of India’s 19...,The 1947 Partition Archive began with the need...,2011,http://www.1947PartitionArchive.org,"Education, Arts & Culture, Human Rights",Global,"Berkeley, California, United States","Web, Hardware","$0 to $500,000",...,None,None,https://www.linkedin.com/in/guneeta,None,None,None,None,None,None,None
1,A Way Home Washington,We believe that we can prevent and end youth h...,A Way Home Washington provides statewide suppo...,2019,https://awayhomewa.org/,"Human Rights, Public Service & Civic Engagement",United States,"Seattle, Washington, United States",Web,"$1,000,000 +",...,None,None,https://campionadvocacyfund.org/people/sonya-...,https://awayhomewa.org/about-us/,None,None,None,None,None,None
2,AccesSOS,To make it possible for people with limited En...,AccesSOS was started because the founder’s Dea...,2019,https://accessos.io,"Health & Healthcare, Public Service & Civic En...",United States,"San Francisco, California, United States",Mobile Apps,"$0 to $500,000",...,None,None,https://www.linkedin.com/in/gabriella-m/,https://www.linkedin.com/in/sarah-peterson-444...,None,None,None,None,None,None
3,AbleThrive,AbleThrive makes it easier for families to fin...,"When a family faces a disability, they are oft...",2014,http://www.ablethrive.com,"Health & Healthcare, Public Service & Civic En...",Global,"Downingtown, Pennsylvania, United States",Web,"$0 to $500,000",...,None,None,https://sg.linkedin.com/in/brittanym,None,None,None,None,None,None,None
4,Acquaint,"Crowdsourcing a peaceful, more inclusive world...","Acquaint is a rewarding, inclusive, and access...",2021,https://www.acquaint.org?tsrc=nl1_ffwd1,"Public Service & Civic Engagement, Arts & Cult...",Global,"Bellevue, Washington, United States",Web,"$0 to $500,000",...,None,None,https://www.linkedin.com/in/katherine-mahon1/,https://www.linkedin.com/in/alex-szebenyi/,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
716,Zariya,Zariya’s on a mission to ensure that every wom...,Zariya is an organization that addresses the p...,2015,http://www.zariyaindia.org,"Human Rights, Poverty Alleviation & Economic D...",India,"Stanford, California, United States","Web, Mobile Apps","$0 to $500,000",...,None,None,https://www.linkedin.com/in/khansahar,https://www.linkedin.com/in/arzavjain,https://www.linkedin.com/in/abraham-vargheese-...,https://www.linkedin.com/in/japsimran-kaur-9b3...,None,None,None,None
717,ZAKKI (Integrity Syariah),Empowering the marginalized economic community...,"ZAKKI, is a non profit entity that focuses on ...",2018,https://www.zakki.org,"Poverty Alleviation & Economic Development, Pu...",Indonesia,"Semarang, Indonesia","Web, Mobile Apps","$0 to $500,000",...,None,None,https://www.linkedin.com/in/arifah/,None,None,None,None,None,None,None
718,YWCA Golden Gate Silicon Valley,YWCA Silicon Valley is dedicated to eliminatin...,In addition to our work in disrupting the cycl...,2017,https://ywca-sv.org/curated-pathways-to-innova...,"Education, Poverty Alleviation & Economic Deve...",United States,"San Jose, California, United States",Mobile Apps,"$500,000 to $1,000,000",...,None,None,https://www.linkedin.com/in/janice-zdankus-a4...,https://www.linkedin.com/in/lesley-slaton-brow...,None,None,None,None,None,None
719,YTH,Youth + Tech + Health is the partner of choice...,Youth + Technology + Health. YTH is committed ...,2001,http://yth.org,"Public Service & Civic Engagement, Health & He...","Global, Africa, Latin America, United States","Oakland , California, United States","Web, Mobile Apps, SMS","$1,000,000 +",...,None,None,https://www.linkedin.com/in/deblevine,None,None,None,None,None,None,None
720,Zooniverse,The Zooniverse is a collection of web-based Ci...,The Zooniverse is the largest online platform ...,2008,https://www.zooniverse.org/,Environment,Global,"Chicago , Illinois, United States","Web, Mobile Apps","$500,000 to $1,000,000",...,None,None,https://www.linkedin.com/in/chris-lintott-621...,None,None,None,None,None,None,None

In [43]:
df.to_csv('ffwdCleanedData.csv',index=False)