In [14]:
import pandas as pd

df = pd.read_csv('Steam_reviews.csv')
df

,Date,Reaction,Review
0,"Posted: February 26, 2022",\r\n\t\t\t\t993 people found this review helpf...,\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tHighly rec...
1,"Posted: August 1, 2019",\r\n\t\t\t\t659 people found this review helpf...,\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tGTA V sing...
2,"Posted: March 2, 2021",\r\n\t\t\t\t941 people found this review helpf...,\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ti ran over...
3,"Posted: July 27, 2021",\r\n\t\t\t\t691 people found this review helpf...,\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tGTA Online...
4,Posted: June 13,"\r\n\t\t\t\t2,620 people found this review hel...",\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tNewest upd...
...,...,...,...
497,Posted: November 12,\r\n\t\t\t\t1 person found this review helpful...,\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tGame of De...
498,Posted: November 11,\r\n\t\t\t\t1 person found this review helpful...,\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\thalf of my...
499,Posted: November 11,\r\n\t\t\t\t1 person found this review helpful...,\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tRockstar l...
500,Posted: November 11,\r\n\t\t\t\t1 person found this review helpful...,\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ti made mon...
501,Posted: November 11,\r\n\t\t\t\t1 person found this review helpful...,\r\n\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tgood\t\t\t

In [15]:
df['Reaction'] = df['Reaction'].str.strip()
df['Review'] = df['Review'].str.strip()
df

,Date,Reaction,Review
0,"Posted: February 26, 2022","993 people found this review helpful,864 peopl...",Highly recommend for young children to learn m...
1,"Posted: August 1, 2019","659 people found this review helpful,210 peopl...","GTA V singleplayer,100% fun,GTA V online,40% l..."
2,"Posted: March 2, 2021","941 people found this review helpful,474 peopl...",i ran over a person
3,"Posted: July 27, 2021","691 people found this review helpful,410 peopl...",GTA Online is the proof that world peace canno...
4,Posted: June 13,"2,620 people found this review helpful,72 peop...",Newest update removed ~180 cars from the game....
...,...,...,...
497,Posted: November 12,"1 person found this review helpful\t\t\t\t,0",Game of Decades
498,Posted: November 11,"1 person found this review helpful\t\t\t\t,0",half of my hours in this game were spent loadi...
499,Posted: November 11,"1 person found this review helpful\t\t\t\t,0",Rockstar launcher says my steam is linked to a...
500,Posted: November 11,"1 person found this review helpful\t\t\t\t,0",i made money hack on online my dad is proud of me
501,Posted: November 11,"1 person found this review helpful\t\t\t\t,0",good

In [16]:
df.to_csv('Steam_GTA_V.csv',index=False)